name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  # We'll handle the lowercase conversion in a step later
  DOCKER_USERNAME: akhil836
  DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm install
        npm install mocha --save-dev
        
    - name: Run tests
      run: |
        echo "Running tests..."
        npx mocha test.js --exit
        
    - name: Verify server starts
      run: |
        npm start &
        sleep 5
        curl http://localhost:3000

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Convert repository name to lowercase
      id: repo-name
      run: |
        # Convert repository name to lowercase
        LOWERCASE_REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "lowercase_repo=${LOWERCASE_REPO}" >> $GITHUB_OUTPUT
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ steps.repo-name.outputs.lowercase_repo }}:latest
          ${{ env.DOCKER_USERNAME }}/${{ steps.repo-name.outputs.lowercase_repo }}:${{ github.sha }}
